# Site settings
# GitHub Pages root site for https://ponyyuhan.github.io/
title: "Yuhan Ma"
description: "Academic homepage of Yuhan Ma."
url: "https://ponyyuhan.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Europe/Berlin

collections:
  - publications
  - news
  - showcase
  - posts
